"""Messages and the tool calls that come with them.

These two tables are what let you reopen an old conversation and see EXACTLY
what happened: not just the final answer, but also what the assistant looked
up, with which arguments, how long it took, and whether it succeeded or failed.

Why tool calls get their own table instead of being stuffed into the message's
JSON: later statistics ("which tool fails most often", "how long does it take on
average") then need a single query, not JSON unpacking.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.db.models.thread import ChatThread

ROLES = ("user", "assistant", "system")
MESSAGE_STATUSES = ("streaming", "complete", "error")
TOOL_STATUSES = ("running", "ok", "error")


class Message(Base, TimestampMixin):
    __tablename__ = "messages"
    __table_args__ = (
        # Constraint names are kept as-is: they already exist in the migrations,
        # and renaming them requires a dedicated migration.
        CheckConstraint("role IN ('user', 'assistant', 'system')", name="role_hop_le"),
        CheckConstraint(
            "status IN ('streaming', 'complete', 'error')", name="status_hop_le"
        ),
        # Two messages in the same conversation must not share a position.
        UniqueConstraint("thread_id", "position", name="uq_messages_thread_position"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    thread_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("chat_threads.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    role: Mapped[str] = mapped_column(String(16), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # What the model thought before answering. Stored so that reopening an old
    # conversation still shows how it reasoned — that is often the only place
    # that explains why the assistant chose to look up one thing and not another.
    # NULL for user messages, and for providers that do not expose reasoning.
    reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Order within the conversation, starting at 1. Not based on created_at
    # because two messages can be written within the same millisecond.
    position: Mapped[int] = mapped_column(Integer, nullable=False)

    status: Mapped[str] = mapped_column(String(16), nullable=False, default="complete")
    error: Mapped[str | None] = mapped_column(Text, nullable=True)

    # --- Traces for later inspection (observability use case) ---
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    provider: Mapped[str | None] = mapped_column(String(40), nullable=True)
    model: Mapped[str | None] = mapped_column(String(120), nullable=True)
    prompt_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    completion_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    latency_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)

    thread: Mapped[ChatThread] = relationship(back_populates="messages", lazy="raise")
    tool_calls: Mapped[list[ToolCall]] = relationship(
        back_populates="message",
        cascade="all, delete-orphan",
        order_by="ToolCall.started_at",
        lazy="raise",
    )

    def __repr__(self) -> str:
        return f"<Message {self.role} #{self.position} {self.content[:30]!r}>"


class ToolCall(Base, TimestampMixin):
    __tablename__ = "tool_calls"
    __table_args__ = (
        CheckConstraint("status IN ('running', 'ok', 'error')", name="status_hop_le"),
        # `call_id` is generated by LangGraph; a duplicate within one message is a
        # pairing bug.
        UniqueConstraint("message_id", "call_id", name="uq_tool_calls_message_call"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    message_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("messages.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Id used to pair tool_call_start with tool_call_end on the wire.
    call_id: Mapped[str] = mapped_column(String(64), nullable=False)
    name: Mapped[str] = mapped_column(String(120), nullable=False, index=True)
    args: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)

    # Shortened version for display. The full version lives in Langfuse.
    result: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="running")
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    duration_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    message: Mapped[Message] = relationship(back_populates="tool_calls", lazy="raise")

    def __repr__(self) -> str:
        return f"<ToolCall {self.name} {self.status}>"
