"use client";

import { memo } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

import { cn } from "@/lib/utils";

/**
 * Renders the assistant's answer as markdown.
 *
 * SECURITY — the most important part of this file:
 *
 * This content is generated by the MODEL, and the model has just read logs and
 * error messages pulled from the Kubernetes cluster. So an attacker who can get
 * an arbitrary string into a pod's logs has a direct path to the on-call
 * engineer's browser.
 *
 * Therefore NEVER add `rehype-raw` or `dangerouslySetInnerHTML`. By default
 * react-markdown escapes all raw HTML — `<script>` shows up as text instead of
 * running. Keep it that way.
 *
 * Links are also something the model can make up, so they open in a new tab
 * with `noopener noreferrer nofollow`, and react-markdown filters the protocol
 * (blocking `javascript:`).
 */

const BLOCK = "my-2 first:mt-0 last:mb-0";

interface Props {
  children: string;
  className?: string;
}

function MarkdownBase({ children, className }: Props) {
  return (
    <div className={cn("text-sm leading-relaxed", className)}>
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          p: ({ children }) => <p className={BLOCK}>{children}</p>,

          // Lists: used the most, since the assistant often enumerates checks to run.
          ul: ({ children }) => (
            <ul className={cn(BLOCK, "list-disc space-y-1 pl-5")}>{children}</ul>
          ),
          ol: ({ children }) => (
            <ol className={cn(BLOCK, "list-decimal space-y-1 pl-5")}>{children}</ol>
          ),
          li: ({ children }) => <li className="pl-0.5">{children}</li>,

          strong: ({ children }) => (
            <strong className="font-semibold">{children}</strong>
          ),
          em: ({ children }) => <em className="italic">{children}</em>,

          // kubectl commands are often wider than the chat pane, so code blocks must
          // scroll horizontally. Without it the whole page gets pushed wider.
          pre: ({ children }) => (
            <pre
              className={cn(
                BLOCK,
                "overflow-x-auto rounded-md bg-[var(--muted)] p-3 text-xs leading-relaxed",
                "[&_code]:bg-transparent [&_code]:p-0 [&_code]:text-xs",
              )}
            >
              {children}
            </pre>
          ),
          code: ({ children, ...props }) => (
            <code
              className="rounded bg-[var(--muted)] px-1 py-0.5 font-mono text-[0.85em]"
              {...props}
            >
              {children}
            </code>
          ),

          a: ({ children, href }) => (
            <a
              href={href}
              target="_blank"
              rel="noopener noreferrer nofollow"
              className="underline underline-offset-2 hover:opacity-80"
            >
              {children}
            </a>
          ),

          // Headings inside the chat must stay small — this is a message, not a
          // documentation page.
          h1: ({ children }) => (
            <h3 className={cn(BLOCK, "text-base font-semibold")}>{children}</h3>
          ),
          h2: ({ children }) => (
            <h3 className={cn(BLOCK, "text-sm font-semibold")}>{children}</h3>
          ),
          h3: ({ children }) => (
            <h4 className={cn(BLOCK, "text-sm font-semibold")}>{children}</h4>
          ),
          h4: ({ children }) => (
            <h4 className={cn(BLOCK, "text-sm font-medium")}>{children}</h4>
          ),

          blockquote: ({ children }) => (
            <blockquote
              className={cn(BLOCK, "border-l-2 pl-3 text-[var(--muted-foreground)]")}
            >
              {children}
            </blockquote>
          ),

          hr: () => <hr className="my-3" />,

          // Tables scroll inside their own frame instead of stretching the whole page.
          table: ({ children }) => (
            <div className={cn(BLOCK, "overflow-x-auto")}>
              <table className="w-full border-collapse text-xs">{children}</table>
            </div>
          ),
          th: ({ children }) => (
            <th className="border px-2 py-1 text-left font-semibold">{children}</th>
          ),
          td: ({ children }) => <td className="border px-2 py-1 align-top">{children}</td>,
        }}
      >
        {children}
      </ReactMarkdown>
    </div>
  );
}

/**
 * Memoized by content.
 *
 * While streaming, every incoming chunk triggers a re-render; without this, the
 * OLD messages in the thread would be re-parsed from scratch along with it.
 */
export const Markdown = memo(MarkdownBase);
