"""them cot reasoning cho messages

Revision ID: cd18dce5b7cb
Revises: 677716bba16d
"""
from alembic import op
import sqlalchemy as sa


revision = 'cd18dce5b7cb'
down_revision = '677716bba16d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reasoning')
    # ### end Alembic commands ###
