"""tools catalog, mcp servers and agent skills

Two layers for the Skills page:
  - TOOLS (code the model calls): tool_settings, mcp_servers, mcp_tools, tool_runs
  - SKILLS (Agent Skills folders): skills, skill_files, skill_runs (script runs)
Autogenerate again proposed dropping the server default of `users.role`; that
unrelated drift was removed.

Revision ID: df3c82e3549e
Revises: f0e04ca322b1
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'df3c82e3549e'
down_revision = 'f0e04ca322b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('token_enc', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_servers')),
    sa.UniqueConstraint('name', name=op.f('uq_mcp_servers_name'))
    )
    op.create_table('skill_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill', sa.String(length=64), nullable=False),
    sa.Column('script', sa.String(length=200), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_runs'))
    )
    op.create_index(op.f('ix_skill_runs_created_at'), 'skill_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_skill_runs_skill'), 'skill_runs', ['skill'], unique=False)
    op.create_table('mcp_tools',
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_only_hint', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], name=op.f('fk_mcp_tools_server_id_mcp_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'name', name=op.f('pk_mcp_tools'))
    )
    op.create_table('skills',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_skills_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_skills_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_skills'))
    )
    op.create_table('tool_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_tool_runs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_runs'))
    )
    op.create_index(op.f('ix_tool_runs_created_at'), 'tool_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_tool_runs_tool'), 'tool_runs', ['tool'], unique=False)
    op.create_table('tool_settings',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('danger', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_tool_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_tool_settings'))
    )
    op.create_table('skill_files',
    sa.Column('skill_name', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_name'], ['skills.name'], name=op.f('fk_skill_files_skill_name_skills'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_name', 'path', name=op.f('pk_skill_files'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_files')
    op.drop_table('tool_settings')
    op.drop_index(op.f('ix_tool_runs_tool'), table_name='tool_runs')
    op.drop_index(op.f('ix_tool_runs_created_at'), table_name='tool_runs')
    op.drop_table('tool_runs')
    op.drop_table('skills')
    op.drop_table('mcp_tools')
    op.drop_index(op.f('ix_skill_runs_skill'), table_name='skill_runs')
    op.drop_index(op.f('ix_skill_runs_created_at'), table_name='skill_runs')
    op.drop_table('skill_runs')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
