"""Generate and look up `trace_id` — the thread tying every piece of observability together.

WHY THIS FILE EXISTS

The system writes `trace_id` to the `messages` table BEFORE the LangGraph graph
runs, because the id must already exist to be sent along to the UI. If
Langfuse were left to generate its own id, we would have two different ids for
the same chat turn:

    messages.trace_id   =  a1b2...      (generated by us)
    Langfuse trace      =  f9e8...      (generated by the SDK)

Then `impact.py` could join nothing at all — and joining `trace <-> audit log`
is the whole reason the observability module exists. So the rule is:

    WE generate the id first, then FORCE Langfuse to use exactly that id.

The format must be a valid OpenTelemetry trace id: 128 bits, written as 32 hex
characters, and non-zero. `uuid.uuid4().hex` happens to be 32 hex characters
too, so it looks similar, but it fixes some bits for the UUID version and
variant — usable, but not what OTel expects. Here we use Langfuse's own
generator when available, otherwise 128 random bits.
"""

from __future__ import annotations

import logging
import secrets

logger = logging.getLogger(__name__)

#: An all-zero trace id is the value OTel uses to signal "no trace".
_EMPTY_TRACE_ID = "0" * 32


def new_trace_id() -> str:
    """Generate a new trace id in OpenTelemetry format (32 hex characters)."""
    try:
        from langfuse import Langfuse

        return Langfuse.create_trace_id()
    except Exception:
        # langfuse not installed, or the SDK changed its API. No problem: 128
        # random bits is still a valid trace id.
        return secrets.token_hex(16)


def current_trace_id() -> str | None:
    """Trace id of the active span, or None if not inside any trace.

    Used when a trace id needs to be attached to a secondary record (an audit
    log entry, say) without conveniently passing it all the way down.
    """
    try:
        from opentelemetry import trace as otel_trace
    except ImportError:
        return None

    span = otel_trace.get_current_span()
    ctx = span.get_span_context()
    if not ctx.is_valid:
        return None

    trace_id = format(ctx.trace_id, "032x")
    return None if trace_id == _EMPTY_TRACE_ID else trace_id


def trace_url(trace_id: str) -> str | None:
    """Link that opens the trace in the Langfuse UI, for the "View trace" button.

    Returns None when Langfuse is disabled, or when the SDK doesn't know the
    project id yet — it only learns it after the first `auth_check()` call.
    Callers must tolerate None and simply not show that button.
    """
    from app.modules.observability.langfuse_client import get_langfuse

    client = get_langfuse()
    if client is None:
        return None

    try:
        return client.get_trace_url(trace_id=trace_id)
    except Exception:
        logger.debug("Could not build the trace link for %s", trace_id, exc_info=True)
        return None


__all__ = ["current_trace_id", "new_trace_id", "trace_url"]
